version: "3.8"

services:
  tunneling-utility:
    image: tunneling-utility
    build: ../../Tunneling-Utility
    container_name: tunneling-utility
    environment:
      LT_SUBDOMAIN: nabi-prod-3dlv29zr3ghklrd9
      LT_HOST: reverse-proxy
      LT_PORT: 80
    networks: 
      - rp-network
  reverse-proxy:
    image: reverse-proxy
    build: ../../Reverse-Proxy
    container_name: reverse-proxy
    networks: 
      - pwa-network
      - nlu-network
      - tts-network
      - rp-network

  web-service:
    image: web-service
    build: ../../Nabi-UI
    container_name: web-service
    networks:
      - pwa-network
  listening-service:
    image: listening-service
    build: ../../Nabi-Brain
    container_name: listening-service
    networks:
      - nlu-network
      - rasa-network
  # speaking-service:
  #   image: speaking-service
  #   build: ../../Nabi-Voice
  #   container_name: speaking-service
  #   networks:
  #     - tts-network

  action-server:
    image: action-server
    build: ../../Nabi-Brain/actions
    container_name: action-server
    networks:
      - rasa-network

networks: 
  rp-network:
  pwa-network:
  nlu-network:
  tts-network:
  rasa-network: