version: "3.8"

services:
  tunneling-utility-dev:
    image: registry.shuruni.com:5000/tunneling-utility-dev
    build: ../../utility/Tunneling-Utility/dev
    container_name: tunneling-utility-dev
    networks: 
      - rp-network
  reverse-proxy:
    image: registry.shuruni.com:5000/reverse-proxy
    build: ../../utility/Reverse-Proxy
    container_name: reverse-proxy
    networks: 
      - pwa-network
      - nlu-network
      - tts-network
      - rp-network

  web-service:
    image: registry.shuruni.com:5000/web-service
    build: ../../src/Nabi-UI
    container_name: web-service
    networks:
      - pwa-network
  listening-service:
    image: registry.shuruni.com:5000/listening-service
    build: ../../src/Nabi-Brain
    container_name: listening-service
    networks:
      - nlu-network
      - rasa-network
  action-service:
    image: registry.shuruni.com:5000/action-service
    build: ../../src/Nabi-Brain/actions
    container_name: action-server
    networks:
      - rasa-network
  speaking-service:
    image: registry.shuruni.com:5000/speaking-service
    build: ../../src/Nabi-Voice/service
    container_name: speaking-service
    networks:
      - tts-network

networks: 
  rp-network:
  pwa-network:
  nlu-network:
  tts-network:
  rasa-network: